#!/bin/sh
#
# yes, sleeps are inefficient and potentially inaccurate.  but better
# than nothing for now.

SERVERNAME=opensim-grid-server
SERVER=OpenSim.Grid.GridServer.exe
SERVEROPTS="-gui=true"
OPENSIMDIR=/usr/lib/opensim

if `svok /etc/service/opensim-user-server`; then

    sleep 15
    echo [ `date` ] Starting $SERVERNAME ...
    su - opensim -c "cd ${OPENSIMDIR}/bin; screen -S $SERVERNAME -t $SERVERNAME -D -m mono $SERVER $SERVEROPTS"
    echo [ `date` ] Restarting $SERVERNAME ...

else

    sleep 2

fi
