#!/bin/sh
#
# yes, sleeps are inefficient and potentially inaccurate.  but better
# than nothing for now.

SERVERNAME=opensim-user-server
SERVER=OpenSim.Grid.UserServer.exe
SERVEROPTS="-gui=true"
OPENSIMDIR=/usr/lib/opensim


echo [ `date` ] Starting $SERVERNAME ...

su - opensim -c "cd ${OPENSIMDIR}/bin; screen -S $SERVERNAME -t $SERVERNAME -D -m mono $SERVER $SERVEROPTS"

echo [ `date` ] Restarting $SERVERNAME ...
