#!/bin/sh

SERVERNAME=opensim-messaging-server
SERVER=OpenSim.Grid.MessagingServer.exe
SERVEROPTS="-gui=true"
OPENSIMDIR=/usr/lib/opensim


echo [ `date` ] Starting $SERVERNAME ...

su - opensim -c "cd ${OPENSIMDIR}/bin; screen -S $SERVERNAME -t $SERVERNAME -D -m mono $SERVER $SERVEROPTS"

echo [ `date` ] Restarting $SERVERNAME ...
